// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetV1TransportKmbStopError, GetV1TransportKmbStopResponse, GetV1TransportKmbStopEtaByStopIdData, GetV1TransportKmbStopEtaByStopIdError, GetV1TransportKmbStopEtaByStopIdResponse, GetV1TransportKmbStopByStopIdData, GetV1TransportKmbStopByStopIdError, GetV1TransportKmbStopByStopIdResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Stop List API
 */
export const getV1TransportKmbStop = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetV1TransportKmbStopResponse, GetV1TransportKmbStopError, ThrowOnError>({
    ...options,
    url: '/v1/transport/kmb/stop'
}); };

/**
 * Stop ETA API
 */
export const getV1TransportKmbStopEtaByStopId = <ThrowOnError extends boolean = false>(options: Options<GetV1TransportKmbStopEtaByStopIdData, ThrowOnError>) => { return (options?.client ?? client).get<GetV1TransportKmbStopEtaByStopIdResponse, GetV1TransportKmbStopEtaByStopIdError, ThrowOnError>({
    ...options,
    url: '/v1/transport/kmb/stop-eta/{stop_id}'
}); };

/**
 * Stop API
 */
export const getV1TransportKmbStopByStopId = <ThrowOnError extends boolean = false>(options: Options<GetV1TransportKmbStopByStopIdData, ThrowOnError>) => { return (options?.client ?? client).get<GetV1TransportKmbStopByStopIdResponse, GetV1TransportKmbStopByStopIdError, ThrowOnError>({
    ...options,
    url: '/v1/transport/kmb/stop/{stop_id}'
}); };