// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetV1TransportMtrLrtGetScheduleData, GetV1TransportMtrLrtGetScheduleError, GetV1TransportMtrLrtGetScheduleResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * lrtgetschedule
 */
export const getV1TransportMtrLrtGetSchedule = <ThrowOnError extends boolean = false>(options: Options<GetV1TransportMtrLrtGetScheduleData, ThrowOnError>) => { return (options?.client ?? client).get<GetV1TransportMtrLrtGetScheduleResponse, GetV1TransportMtrLrtGetScheduleError, ThrowOnError>({
    ...options,
    url: '/v1/transport/mtr/lrt/getSchedule'
}); };