// This file is auto-generated by @hey-api/openapi-ts

import { client, type Options } from '@hey-api/client-fetch';
import type { GetV1TransportMtrLrtGetScheduleData, GetV1TransportMtrLrtGetScheduleError, GetV1TransportMtrLrtGetScheduleResponse } from './types.gen';

/**
 * lrtgetschedule
 */
export const getV1TransportMtrLrtGetSchedule = (options: Options<GetV1TransportMtrLrtGetScheduleData>) => { return (options?.client ?? client).get<GetV1TransportMtrLrtGetScheduleResponse, GetV1TransportMtrLrtGetScheduleError>({
    ...options,
    url: '/v1/transport/mtr/lrt/getSchedule'
}); };