// This file is auto-generated by @hey-api/openapi-ts

export type GetV1TransportMtrLrtGetScheduleData = {
    query: {
        /**
         * Station id of LR station
         */
        station_id: number;
    };
};

export type GetV1TransportMtrLrtGetScheduleResponse = {
    platform_list: Array<{
        route_list: Array<{
            /**
             * The Length of the train
             */
            train_length: number;
            /**
             * A : time act as remain arrival time for normal station
             * D : time act as remain departure time for terminal station
             */
            arrival_departure: string;
            /**
             * Destination of the route in English
             */
            dest_en: string;
            /**
             * Destination of the route in Chinese
             */
            dest_ch: string;
            /**
             * Arrival time/departure time in English
             * departing: the train is departing from
             * terminus soon
             * arriving: the train is arriving soon
             * “-”: the train is arriving / departing
             */
            time_en: string;
            /**
             * Arrival time/departure time in Chinese
             * “正在離開”: the train is departing from
             * terminus soon
             * “即將抵達”: the train is arriving soon
             * “-”:the train is arriving / departing
             */
            time_ch: string;
            /**
             * Route number
             */
            route_no: string;
            /**
             * Indicate the line is stopped
             */
            stop: number;
        }>;
        /**
         * Platform id of each station
         */
        platform_id: number;
    }>;
    /**
     * system status code value: "1" = normal “0” = error or alert
     */
    status: number;
    /**
     * System date and time
     */
    system_time: string;
};

export type GetV1TransportMtrLrtGetScheduleError = unknown;

export type $OpenApiTs = {
    '/v1/transport/mtr/lrt/getSchedule': {
        get: {
            req: GetV1TransportMtrLrtGetScheduleData;
            res: {
                /**
                 * LrtSuccessfulGetSchedule
                 */
                '200': {
                    platform_list: Array<{
                        route_list: Array<{
                            /**
                             * The Length of the train
                             */
                            train_length: number;
                            /**
                             * A : time act as remain arrival time for normal station
                             * D : time act as remain departure time for terminal station
                             */
                            arrival_departure: string;
                            /**
                             * Destination of the route in English
                             */
                            dest_en: string;
                            /**
                             * Destination of the route in Chinese
                             */
                            dest_ch: string;
                            /**
                             * Arrival time/departure time in English
                             * departing: the train is departing from
                             * terminus soon
                             * arriving: the train is arriving soon
                             * “-”: the train is arriving / departing
                             */
                            time_en: string;
                            /**
                             * Arrival time/departure time in Chinese
                             * “正在離開”: the train is departing from
                             * terminus soon
                             * “即將抵達”: the train is arriving soon
                             * “-”:the train is arriving / departing
                             */
                            time_ch: string;
                            /**
                             * Route number
                             */
                            route_no: string;
                            /**
                             * Indicate the line is stopped
                             */
                            stop: number;
                        }>;
                        /**
                         * Platform id of each station
                         */
                        platform_id: number;
                    }>;
                    /**
                     * system status code value: "1" = normal “0” = error or alert
                     */
                    status: number;
                    /**
                     * System date and time
                     */
                    system_time: string;
                };
            };
        };
    };
};